### PR TITLE
COMP: Unused parameters argument to SetParameters

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by thewtex** [comment]
New GitHub comment: yadda yadda

**Comment by thewtex** [comment]
View build and test results for change [1491f90642f2c87a30828c86edef0f99e18ccd94](undefined) on [CDash](https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=${CDASHPROJECT}&showfilters=0&limit=100&value1=${COMMIT}&showfeed=0)

**Comment by thewtex** [comment]
View build and test results for change [1491f90](https://api.github.com/repos/thewtex/ITKPolarTransform/compare/{base}...{head}) on [CDash](https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=${CDASHPROJECT}&showfilters=0&limit=100&value1=${COMMIT}&showfeed=0)

**Comment by thewtex** [comment]
View build and test results for change [1491f90](https://api.github.com/repos/thewtex/ITKPolarTransform/compare/d9596104a8477ba15c27a1659ff2882541dcdd86...1491f90642f2c87a30828c86edef0f99e18ccd94) on [CDash](https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=Insight&showfilters=0&limit=100&value1=1491f90&showfeed=0)

**Pull request merged**
